### ISSUE TITLE
Error installing on Rocky Linux 8

### ISSUE THREAD

**Issue by RevengeFNF** [madeITBelgium/vesta#114]
### Operating System (OS/VERSION):

Rocky Linux 8

### VestaCP Version:

0.0.33

### Installed Software (what you got with the installer):

php-fpm, nginx, MariaDB

### Steps to Reproduce:

Rocky Linux 8 is the same thing as Centos 8, and im getting this error when installing:

`Last metadata expiration check: 0:00:37 ago on Sat 06 Nov 2021 07:49:30 PM UTC.
Package curl-7.61.1-18.el8_4.2.x86_64 is already installed.
Package e2fsprogs-1.45.6-1.el8.1.x86_64 is already installed.
Package freetype-2.9.1-4.el8_3.1.x86_64 is already installed.
Package chrony-3.5-2.el8.x86_64 is already installed.
Package openssh-clients-8.0p1-6.el8_4.2.x86_64 is already installed.
Package pcre-8.42-4.el8.x86_64 is already installed.
Package php-cli-8.0.12-1.el8.remi.x86_64 is already installed.
Package php-common-8.0.12-1.el8.remi.x86_64 is already installed.
Package php-fpm-8.0.12-1.el8.remi.x86_64 is already installed.
Package php-mbstring-8.0.12-1.el8.remi.x86_64 is already installed.
Package php-xml-8.0.12-1.el8.remi.x86_64 is already installed.
Package rsyslog-8.1911.0-7.el8_4.2.x86_64 is already installed.
Package sudo-1.8.29-7.el8_4.1.x86_64 is already installed.
Package which-2.21-12.el8.x86_64 is already installed.
Error: 
 Problem: conflicting requests
  - nothing provides perl(Switch) needed by awstats-7.8-2.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Error: yum install failed`

**Comment by madeITBelgium** [comment]
Can you try the following command before installing?
`dnf install -y perl`

**Comment by Darkmensager** [comment]
I did that now in a new server, it installed a bunch of Perl files, then i installed your Vesta, but same error occurred.

**Comment by madeITBelgium** [comment]
Hi @Darkmensager,
Can you enable PowerTools repo?

For AlmaLinux it is this file: /etc/yum.repos.d/almalinux-powertools.repo

Maybe you can give me the correct path for rockylinux? Then I can fix that in the installer.
https://github.com/madeITBelgium/vesta/blob/master/install/vst-install-rhel-8.sh#L453-L456

**Comment by Darkmensager** [comment]
``Hello,

Sorry for the delay.

For Rocky Linux 8 it is this file: /etc/yum.repos.d/Rocky-PowerTools.repo

If you need, the other repos are this ones:

[https://i.imgur.com/Sjeceuf.png](url)

I enabled manually the powertools repo, and that error doesn't happen anymore. 
But now i got another error and the installation stops there:

`Complete!
Redirecting to /bin/systemctl stop iptables.service
Redirecting to /bin/systemctl stop ip6tables.service
mkdir: cannot create directory â€˜/etc/systemd/system/nginx.service.d/â€™: File exists
Note: Forwarding request to 'systemctl enable nginx.service'.
Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service â†’ /usr/lib/systemd/system/nginx.service.
Redirecting to /bin/systemctl start nginx.service
Note: Forwarding request to 'systemctl enable php-fpm.service'.
Created symlink /etc/systemd/system/multi-user.target.wants/php-fpm.service â†’ /usr/lib/systemd/system/php-fpm.service.
Redirecting to /bin/systemctl start php-fpm.service
Note: Forwarding request to 'systemctl enable vsftpd.service'.
Created symlink /etc/systemd/system/multi-user.target.wants/vsftpd.service â†’ /usr/lib/systemd/system/vsftpd.service.
Redirecting to /bin/systemctl start vsftpd.service
Job for vsftpd.service failed because the control process exited with error code.
See "systemctl status vsftpd.service" and "journalctl -xe" for details.
Error: vsftpd start failed`

Checking the journal, this is the reason:

`vsftpd[42636]: 500 OOPS: missing value in config file for: <<<<<<< HEAD:install/os-configs/rhel/general/vsftpd/vsftpd.conf`

**Comment by madeITBelgium** [comment]
The installation should now work again. There were some issues with the builds which are now fixed
